spring:
  datasource:
    url: jdbc:h2:mem:launchpad-db
  h2:
    console:
      enabled: false
      path: /h2
  jpa:
    open-in-view: false

launchpad:
  settings:
    path: "/etc/launchpad/settings.json"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8000
