spring:
  datasource:
    url: jdbc:h2:mem:launchpad-db
  h2:
    console:
      enabled: false
      path: /h2
  jpa:
    open-in-view:launchpad: false
  settings:
    path: "/opt/launchpad/settings.json"

server:
  port: 8000