create table file
(

    id        bigint generated by default as identity,
    name      varchar(255) not null,
    directory varchar(4096) not null,
    path      varchar(4096) not null,
    created   timestamp(6) with time zone,
    modified  timestamp(6) with time zone,
    primary key (id)
);

create index IDX_FILE__path
    on file(path);


create table video
(
    id       bigint generated by default as identity,
    name     varchar(255),
    file_id  bigint unique,
    modified timestamp(6) with time zone,
    created  timestamp(6) with time zone,
    primary key (id)
);

create index IDX_VIDEO__NAME
    on video (name);

alter table video
    add constraint FK_VIDEO__FILE_ID
    foreign key (file_id)
    references file;
